# Generated by Django 5.1.2 on 2024-10-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facecolda',
            options={'managed': False},
        ),
    ]
