# Generated by Django 4.2.16 on 2024-11-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_facecolda_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facecolda',
            table='ValoresFasecolda',
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cliente_id', models.IntegerField()),
                ('placa', models.CharField(max_length=20)),
                ('lugar', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('rechazada', 'Rechazada'), ('aceptada', 'Aceptada')], default='pendiente', max_length=10)),
            ],
            options={
                'unique_together': {('fecha', 'hora', 'lugar')},
            },
        ),
    ]
