# Generated by Django 4.2.16 on 2024-11-25 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_delete_inspeccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('n_identificacion', models.CharField(max_length=20)),
                ('tipo_identificacion', models.CharField(max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('contraseña', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('marca_vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano_vehiculo', models.IntegerField()),
                ('identificacion_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cobertura', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_asegurado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('identificacion_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuario')),
            ],
        ),
    ]
