runtime: nodejs
env: flex
runtime_config:
  operating_system: ubuntu22

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

entrypoint: npm start 

handlers:
  - url: /static
    static_dir: dist/seguros-confianza/browser  # Asegúrate de que esta ruta apunte a 'browser' correctamente

  - url: /.*
    static_files: dist/seguros-confianza/browser/index.html  # Asegúrate de que esta ruta sea correcta
    upload: dist/seguros-confianza/browser/index.html

skip_files:
  - ^node_modules/
  - ^.*/node_modules/
  - ^src/
  - ^e2e/
  - ^\.git/
  - ^\.vscode/
  - ^\.angular/
  - ^coverage/
  - ^.*\.json$
  - ^.*\.md$
  - ^LICENSE
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.bak$