# Generated by Django 4.2.16 on 2024-10-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facecolda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('homologoco', models.IntegerField()),
                ('marca', models.CharField(max_length=100)),
                ('referencia1', models.CharField(max_length=100)),
                ('referencia2', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia3', models.CharField(blank=True, max_length=100, null=True)),
                ('um', models.CharField(max_length=50)),
            ],
        ),
    ]
