# Generated by Django 4.2.16 on 2024-11-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_facecolda_table_inspeccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inspeccion',
        ),
    ]
